# Generated by Django 4.2.7 on 2026-04-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='test_reports',
            field=models.TextField(blank=True, help_text='Lab results, vitals, percentages', null=True),
        ),
    ]
